### ISSUE TITLE
Please HELP~

### ISSUE THREAD

**Issue by kaixinbaba** [dawidd6/action-homebrew-bump-formula#43]
Here's my `workflow.yml`
```yml
 bump-homebrew-formula:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Bump Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          # Required, custom GitHub access token with the 'public_repo' and 'workflow' scopes
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          # Optional, will create tap repo fork in organization
          # org: ORG
          # Optional, defaults to homebrew/core
          # tap: USER/REPO
          # Formula name, required
          formula: hg-tui
          # Optional, will be determined automatically
          tag: ${{github.ref}}
          # Optional, will be determined automatically
          revision: ${{github.sha}}
          # Optional, if don't want to check for already open PRs
          # force: false # true
```
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/22809336/167543362-76c9d3b3-55b4-4aa8-adcc-e47b82866c3a.png">

But got this action error:

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/22809336/167543534-ecbe7d6c-4bef-4ebb-9090-9caf365ec544.png">

Please HELP, What can I do to fix this?
