### ISSUE TITLE
GitHub::API::AuthenticationFailedError

### ISSUE THREAD

**Issue by deadc0de6** [dawidd6/action-homebrew-bump-formula#44]
Hello, I'm not sure what I'm doing wrong. Thanks for your help!

<img width="927" alt="Screenshot 2022-06-26 at 21 17 02" src="https://user-images.githubusercontent.com/8973919/175830428-20459f51-ec24-4b51-b933-2406cfeea1c4.png">

Here's my *Personal access tokens*:

<img width="414" alt="Screenshot 2022-06-26 at 21 17 23" src="https://user-images.githubusercontent.com/8973919/175830438-d4f388b7-5102-4e1d-a1dc-be19e9b4a8e1.png">

Here's my action:
```yaml
name: Release to Homebrew
on:
  release:
    types: [created]
jobs:
  homebrew-core:
    runs-on: macos-latest
    steps:
    - uses: dawidd6/action-homebrew-bump-formula@v3
      with:
        token: ${{secrets.HOMEBREW_FORMULA_GH_TOKEN}}
        formula: dotdrop
```
